#
# Recommended release workflow
#
# Development:
#   git checkout develop
#   git pull origin develop
#   pdm format
#   pdm check-style
#   pdm check-types
#   pdm all-tests
#
# Determine version:
#   pdm bump suggest
#   pdm bump pre-release --pre alpha              # creates 0.1.1a1 from 0.1.0
#   pdm bump pre-release --pre beta               # creates 0.1.1b1 from 0.1.1a1
#   pdm bump pre-release --pre release-candidate  # creates 0.1.1rc1 from 0.1.1b1
#   pdm bump no-pre-release                       # creates 0.1.1 from 0.1.1rc1
#   pdm bump micro                                # creates 0.1.2 from 0.1.1
#   pdm bump minor                                # creates 0.2.0 from 0.1.2
#   pdm bump major                                # creates 1.0.0 from 0.2.0
#
# Prepare release:
#   pdm install -G release   # Install release tools if needed
#   pdm update-license       # Update LICENSE.txt
#   pdm release-notes --tag v1.1.1  # Update CHANGELOG.md. Inspect and verify.
#   git log v1.1.1..HEAD --oneline > log.txt
#   git add .
#   git commit
#   git push
#
# Release:
#  Merge develop into master:
#   git checkout master
#   git pull origin master
#   git merge --no-ff develop
#   git push origin master                        # Wait for CI to complete successfully
#
# Create and publish release tag:
#   pdm bump tag                                  # creates a git tag with a leading v
#   git push --tags                               # publish the new version
#
# Note:
# Publishing to PyPI occurs when a tag beginning with 'v'
# is pushed and the GitHub release workflow succeeds.
#
# Rebuilding the lock files:
#   pdm lock-all
#
# After the release, merge master back into develop
# so that release commits and version changes are present in develop:
#   git checkout develop
#   git pull origin develop
#   git merge master
#   git push origin develop


[project]
name = "karney"
dynamic = ["version"]
description = "Solves the direct and inverse geodesic problem."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }

authors = [
    { name = "Per A. Brodtkorb", email = "per.andreas.brodtkorb@gmail.com" },
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering :: GIS",
]

dependencies = [
    "numpy>=2.0",
]

[project.urls]
Homepage = "https://github.com/pbrod/karney"
Documentation = "https://karney.readthedocs.io/en/latest/"
Repository = "https://github.com/pbrod/karney"
Changelog = "https://github.com/pbrod/karney/blob/main/CHANGELOG.md"

[project.optional-dependencies]
# Used by Read the Docs
docs = [
    "jupyter",
    "myst-nb",
    "sphinx>=8",
    "sphinx-autoapi>=3",
    "sphinx-rtd-theme",
]

[dependency-groups]

test = [
    "hypothesis>=6",
    "mypy>=1.18",
    "pytest>=8",
    "pytest-cov>=7",
    "ruff>=0.13",
]

# Keep synchronized with [project.optional-dependencies.docs]
# Required because Read the Docs doesn't understand PDM dependency groups
docs = [
    "jupyter",
    "myst-nb",
    "sphinx>=8",
    "sphinx-autoapi>=3",
    "sphinx-rtd-theme",
]

release = [
    "git-cliff>=2",
    "pdm-bump>=0.9",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.version]
source = "file"
path = "src/karney/__init__.py"

[tool.pdm.scripts]

docs-html = "sphinx-build -b html docs docs/_build/html"
docs-latex = "sphinx-build -b latex docs docs/_build/latex"
docs-pdf = "sphinx-build -b latexpdf docs docs/_build/latex"
docs-doctest = "sphinx-build -b doctest docs docs/_build/doctest -d docs/_build/doctrees"
lock = "pdm lock -dG all"
lock-py314 = "pdm lock -L pdm.lock314 --python 3.14 --strategy no_direct_minimal_versions -dG all"
lock-all = {composite = ["lock", "lock-py314"]}

format = "ruff format ."
check-style = "ruff check ."
check-types = "mypy src/"
test = "pytest tests/ --cov=karney --cov-report=xml --doctest-modules"
all-tests = {composite = ["format", "check-style", "check-types", "test", "docs-doctest"]}

show-version = "pdm show --version"
show-next-version = "git-cliff --bumped-version"  # calculate and print the next semantic version to stdout:
show-next-changelog = "git-cliff"

update-license = "python update_license.py"

# Example:
# pdm release-notes --tag v1.1.1
release-notes = "git-cliff --prepend CHANGELOG.md"


[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "E4", # pycodestyle import checks
    "E7", # pycodestyle statement checks
    "E9", # pycodestyle runtime checks
    "E501", # pycodestyle linelength checks
    "F",  # PyFlakes
    "I",  # isort
    #"Q",  # flake8-quotes  # ruff already do this
    "UP", # pyupgrade
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.format]
docstring-code-line-length = 100

[tool.mypy]
strict = false
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = true

[tool.pytest.ini_options]
doctest_optionflags = [
    "NORMALIZE_WHITESPACE",
    "IGNORE_EXCEPTION_DETAIL",
    "ELLIPSIS",
]

testpaths = ["tests"]